/*  ---------------------------------------------------------
               __  __            _
              |  \/  |_   _ _ __| |_   _ _ __
              | |\/| | | | | '__| | | | | '_ \
              | |  | | |_| | |  | | |_| | | | |
              |_|  |_|\__, |_|  |_|\__, |_| |_|
                      |___/        |___/
    ---------------------------------------------------------

    Project:  Myrlyn Package Manager GUI
    Copyright (c) Stefan Hundhammer <Stefan.Hundhammer@gmx.de>
    License:  GPL V2 - See file LICENSE for details.

 */


#include <QSettings>

#include "Exception.h"
#include "Logger.h"
#include "MainWindow.h"
#include "SearchFilter.h"
#include "WindowSettings.h"
#include "ZyppHistoryFilterDialog.h"


ZyppHistoryFilterDialog::ZyppHistoryFilterDialog( QWidget * parent )
    : QDialog( parent ? parent : MainWindow::instance() )
    , _ui( new Ui::ZyppHistoryFilterDialog )  // Use the Qt designer .ui form (XML)
{
    CHECK_NEW( _ui );
    _ui->setupUi( this ); // Actually create the widgets from the .ui form

    // See ui_zypp-history-browser.h for the widget names.
    //
    // That header is generated by Qt's uic (user interface compiler)
    // from the XML .ui file created with Qt designer.
    //
    // Take care in Qt designer to give each widget a meaningful name in the
    // widget tree at the top right: They are also the member variable names
    // for the _ui object.

    WindowSettings::read( this, "ZyppHistoryFilterDialog" );
    readSettings();

    connectWidgets();
    initRadioButtons();
}


ZyppHistoryFilterDialog::~ZyppHistoryFilterDialog()
{
    logDebug() << "Destroying ZyppHistoryFilterDialog" << endl;
    
    writeSettings();
    WindowSettings::write( this, "ZyppHistoryFilterDialog" );

    delete _ui;
}


void ZyppHistoryFilterDialog::connectWidgets()
{
    for ( QRadioButton * radioButton: findChildren<QRadioButton *>() )
    {
        connect( radioButton, SIGNAL( toggled           ( bool ) ),
                 this,        SLOT  ( radioButtonToggled( bool ) ) );
    }
}
    
void ZyppHistoryFilterDialog::initRadioButtons()
{
    for ( QRadioButton * radioButton: findChildren<QRadioButton *>() )
        radioButton->setChecked( false );

    _ui->pkgByNameRadioButton->setChecked( true );
}


void ZyppHistoryFilterDialog::radioButtonToggled( bool checked )
{
    if ( ! checked )
        return;
    
    QWidget * radioButton = qobject_cast<QRadioButton *>( sender() );

    _ui->pkgByNameGroupBox->setEnabled( radioButton == _ui->pkgByNameRadioButton );
    _ui->pkgByRepoGroupBox->setEnabled( radioButton == _ui->pkgByRepoRadioButton );
}


void ZyppHistoryFilterDialog::readSettings()
{
    QSettings settings;
    settings.beginGroup( "ZyppHistoryFilterDialog" );

    _ui->pkgByNameSearchMode->setCurrentIndex( settings.value( "pkgByNameSearchMode", 0 ).toInt() );
    _ui->pkgByNameSearchMode->setCurrentIndex( settings.value( "pkgByRepoSearchMode", 0 ).toInt() );

    settings.endGroup();
}


void ZyppHistoryFilterDialog::writeSettings()
{
    QSettings settings;
    settings.beginGroup( "ZyppHistoryFilterDialog" );
    
    settings.setValue( "pkgByNameSearchMode", _ui->pkgByNameSearchMode->currentIndex() );
    settings.setValue( "pkgByRepoSearchMode", _ui->pkgByNameSearchMode->currentIndex() );

    settings.endGroup();
}
